micronaut:
  application:
    name: relatorio-service
  server:
    port: ${SERVER_PORT:8082}

kafka:
  bootstrap:
    servers: ${KAFKA_SERVER:localhost}:${KAFKA_PORT:9092}

mongodb:
  uri: mongodb://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:27017}/vendas

consul:
  client:
    registration:
      enabled: ${CONSUL_ENABLED:true}
    default-zone:
      - ${CONSUL_DEFAULT_ZONE:localhost}:${CONSUL_PORT:8500}