micronaut:
  application:
    name: relatorioService
  server:
    port: -1

kafka:
  bootstrap:
    servers: localhost:9092

mongodb:
  uri: mongodb://localhost:27017/vendas

consul:
  client:
    registration:
      enabled: true
    default-zone:
      - localhost:8500