version: '3'

services:

  relatorio-db:
    container_name: relatorio-db
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: vendas

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - relatorio-db
    ports:
      - '9090:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: relatorio-db
      ME_CONFIG_MONGODB_ADMINPASSWORD: relatorio-db
      ME_CONFIG_MONGODB_URL: mongodb://relatorio-db:relatorio-db@relatorio-db:27017/

  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  loja-redis:
    container_name: loja-redis
    image: redis
    command: redis-server --requirepass lojaService
    ports:
      - "6379:6379"

  veiculo-db:
    container_name: veiculo-db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: veiculodb
      POSTGRES_DB: veiculodb
      POSTGRES_PASSWORD: veiculodb