version: '3'

services:

  relatorio-db:
    container_name: relatorio-db
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: vendas
    networks:
      - ms-network

  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - ms-network

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - ms-network

  loja-redis:
    container_name: loja-redis
    image: redis
    command: redis-server --requirepass lojaService
    ports:
      - "6379:6379"
    networks:
      - ms-network

  veiculo-db:
    container_name: veiculo-db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: veiculodb
      POSTGRES_DB: veiculodb
      POSTGRES_PASSWORD: veiculodb
    networks:
      - ms-network

  consul:
    container_name: consul
    image: bitnami/consul:latest
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    networks:
      - ms-network

  relatorio-service:
    container_name: relatorio-service
    image: relatorio-service
    environment:
      DATASOURCE_HOST: relatorio-db
      DATASOURCE_PORT: 27017
      CONSUL_DEFAULT_ZONE: consul
      CONSUL_PORT: 8500
      CONSUL_ENABLED: true
      KAFKA_SERVER: kafka
      KAFKA_PORT: 9092
    depends_on:
      - relatorio-db
      - kafka
      - consul
    ports:
      - "8082:8082"
    networks:
      - ms-network

  veiculo-service:
    container_name: veiculo-service
    image: veiculo-service
    environment:
      DATASOURCE_HOST: veiculo-db
      DATASOURCE_PORT: 5432
      CONSUL_DEFAULT_ZONE: consul
      CONSUL_PORT: 8500
    depends_on:
      - veiculo-db
      - consul
    ports:
      - "8080:8080"
    networks:
      - ms-network

  loja-service:
    container_name: loja-service
    image: loja-service
    environment:
      REDIS_URI: loja-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: lojaService
      KAFKA_SERVER: kafka
      KAFKA_PORT: 9092
      CONSUL_DEFAULT_ZONE: consul
      CONSUL_PORT: 8500
      CONSUL_ENABLED: true
    depends_on:
      - loja-redis
      - kafka
      - consul
    ports:
      - "8081:8081"
    links:
      - kafka
    networks:
      - ms-network

  gateway-api:
    container_name: gateway-api
    image: gateway-api
    environment:
      CONSUL_DEFAULT_ZONE: consul
      CONSUL_PORT: 8500
    depends_on:
      - consul
    ports:
      - "9999:9999"
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge