version: '3'

services:

  relatorio-db:
    container_name: relatorio-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: relatorio-db
      MONGO_INITDB_ROOT_PASSWORD: relatorio-db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - relatorio-db
    ports:
      - 9090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: relatorio-db
      ME_CONFIG_MONGODB_ADMINPASSWORD: relatorio-db
      ME_CONFIG_MONGODB_URL: mongodb://relatorio-db:relatorio-db@relatorio-db:27017/

  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper